services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "test2" 
      PASSWORD: "abcd@1234"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "400G"
      DISK2_SIZE: "50G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /tmp/windows:/storage
    restart: unless-stopped
    stop_grace_period: 2m
